#!/usr/bin/env python3
"""Packs a llama2.c checkpoint and tokenizer into hooks/weights.ts.

The big matrices are quantized to int8 with one float32 scale per output
row (symmetric, absmax); the RMSNorm vectors stay float32. RoPE tables are
not packed: the runtime recomputes them. Output is one TypeScript module
exporting two base64 strings, which is how a hooks module gets bytes in
(it has no fs of its own for binaries).

usage: pack.py stories260K.bin tok512.bin hooks/weights.ts
"""
import base64
import struct
import sys

from array import array


def main(model_path: str, tok_path: str, out_path: str) -> None:
    raw = open(model_path, "rb").read()
    dim, hidden, layers, heads, kv_heads, vocab, seq_len = struct.unpack("7i", raw[:28])
    shared = vocab > 0
    vocab = abs(vocab)
    head_size = dim // heads
    kv_dim = dim * kv_heads // heads
    floats = array("f"); floats.frombytes(raw[28:])
    if sys.byteorder != "little":
        floats.byteswap()

    cursor = 0

    def take(n: int) -> array:
        nonlocal cursor
        out = floats[cursor : cursor + n]
        cursor += n
        return out

    tok_emb = take(vocab * dim)
    rms_att = take(layers * dim)
    wq = take(layers * dim * dim)
    wk = take(layers * kv_dim * dim)
    wv = take(layers * kv_dim * dim)
    wo = take(layers * dim * dim)
    rms_ffn = take(layers * dim)
    w1 = take(layers * hidden * dim)
    w2 = take(layers * dim * hidden)
    w3 = take(layers * hidden * dim)
    rms_final = take(dim)
    take(seq_len * head_size // 2)  # freq_cis_real, recomputed at runtime
    take(seq_len * head_size // 2)  # freq_cis_imag
    if not shared:
        raise SystemExit("unshared classifier not supported")
    assert cursor == len(floats), (cursor, len(floats))

    out = bytearray()
    out += struct.pack("<7i", dim, hidden, layers, heads, kv_heads, vocab, seq_len)

    def put_f32(a) -> None:
        out.extend(struct.pack(f"<{len(a)}f", *a))

    def put_q8(a: array, cols: int) -> None:
        rows = len(a) // cols
        scales = []
        q = bytearray()
        for r in range(rows):
            row = a[r * cols : (r + 1) * cols]
            amax = max(abs(v) for v in row)
            scale = amax / 127.0 if amax > 0 else 1.0
            scales.append(scale)
            q.extend(struct.pack(f"{cols}b", *(max(-127, min(127, round(v / scale))) for v in row)))
        out.extend(q)
        while len(out) % 4:
            out.append(0)
        put_f32(scales)

    put_q8(tok_emb, dim)
    put_f32(rms_att)
    put_q8(wq, dim)
    put_q8(wk, dim)
    put_q8(wv, dim)
    put_q8(wo, dim)
    put_f32(rms_ffn)
    put_q8(w1, dim)
    put_q8(w2, hidden)
    put_q8(w3, dim)
    put_f32(rms_final)

    tok = open(tok_path, "rb").read()
    model_b64 = base64.b64encode(bytes(out)).decode()
    tok_b64 = base64.b64encode(tok).decode()
    with open(out_path, "w") as f:
        f.write("// Generated by tools/pack.py. Do not edit.\n")
        f.write(f"// TinyStories-260K: dim={dim} hidden={hidden} layers={layers} heads={heads} kv_heads={kv_heads} vocab={vocab}\n")
        f.write(f"// int8 row-quantized weights, {len(out)} bytes; tokenizer {len(tok)} bytes.\n")
        f.write(f"export const MODEL_B64 = '{model_b64}'\n")
        f.write(f"export const TOKENIZER_B64 = '{tok_b64}'\n")
    print(f"packed {len(out)} model bytes + {len(tok)} tokenizer bytes -> {out_path}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
